apiVersion: v1
kind: Service
metadata:
  name: spring-demo
spec:
  selector:
    app: spring-demo
  type: NodePort                # ou LoadBalancer selon Minikube addon
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
