version: "3.9"

services:
  docker:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    ports:
      - "2376:2376"
    volumes:
      - docker_certs:/certs/client

  k3s:
    image: rancher/k3s:v1.32.2-k3s1
    privileged: true
    command:
      - server
      - --https-listen-port=6443
      - --disable=traefik
      - --write-kubeconfig=/output/kubeconfig.yaml
      - --write-kubeconfig-mode=644
      - --tls-san k3s
    environment:
      - K3S_TOKEN=supersecret
    ports:
      - "6443:6443"
    volumes:
      - k3s-data:/var/lib/rancher/k3s
      - k3s-kubeconfig:/output
    healthcheck:
      test: ["CMD", "test", "-f", "/output/kubeconfig.yaml"]
      interval: 10s
      retries: 20

  jenkins:
    build: .
    depends_on:
      - docker
      - sonarqube
      - k3s
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"

      KUBECONFIG: /home/jenkins/.kube/kubeconfig.yaml
      SONAR_HOST_URL: http://sonarqube:9000
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - docker_certs:/certs/client:ro
      - ./scripts:/scripts
      - k3s-kubeconfig:/home/jenkins/.kube
      # ⬇️ retirez les montages Minikube (plus utiles)
      # - ${HOME}/.kube:/home/jenkins/.kube:ro
      # - ${HOME}/.minikube:/home/jenkins/.minikube:ro

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:lts
    depends_on: [db]
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  docker_certs:
  jenkins_home:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:
  k3s-data:
  k3s-kubeconfig:
